package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA43A40)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD9)
val md_theme_light_onPrimaryContainer = Color(0xFF410009)
val md_theme_light_secondary = Color(0xFF9A4056)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9DF)
val md_theme_light_onSecondaryContainer = Color(0xFF3F0016)
val md_theme_light_tertiary = Color(0xFF0B61A4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001C37)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF311300)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF311300)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDC)
val md_theme_light_onSurfaceVariant = Color(0xFF524343)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE4)
val md_theme_light_inverseSurface = Color(0xFF512400)
val md_theme_light_inversePrimary = Color(0xFFFFB3B3)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA43A40)
val md_theme_light_outlineVariant = Color(0xFFD7C1C1)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB3B3)
val md_theme_dark_onPrimary = Color(0xFF650817)
val md_theme_dark_primaryContainer = Color(0xFF84222B)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_secondary = Color(0xFFFFB1C0)
val md_theme_dark_onSecondary = Color(0xFF5F112A)
val md_theme_dark_secondaryContainer = Color(0xFF7C293F)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9DF)
val md_theme_dark_tertiary = Color(0xFFA0C9FF)
val md_theme_dark_onTertiary = Color(0xFF003259)
val md_theme_dark_tertiaryContainer = Color(0xFF00497F)
val md_theme_dark_onTertiaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF311300)
val md_theme_dark_onBackground = Color(0xFFFFDBC7)
val md_theme_dark_surface = Color(0xFF311300)
val md_theme_dark_onSurface = Color(0xFFFFDBC7)
val md_theme_dark_surfaceVariant = Color(0xFF524343)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C1)
val md_theme_dark_outline = Color(0xFFA08C8C)
val md_theme_dark_inverseOnSurface = Color(0xFF311300)
val md_theme_dark_inverseSurface = Color(0xFFFFDBC7)
val md_theme_dark_inversePrimary = Color(0xFFA43A40)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB3B3)
val md_theme_dark_outlineVariant = Color(0xFF524343)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFE56B6F)
